server:
  port: 8080
  forward-headers-strategy: native

spring:
  application:
    name: NBE9-11-final-Team02
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
  profiles:
    active: dev
    include: secret
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always